spring.application.name=ecommerce-api

# Base URL
spring.api.url=http://localhost:8080/api
spring.client.url=http://localhost:8080/api

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20

# JWT Config
jwt.email.verification.token.secret=${JWT_VERIFICATION_EMAIL_SECRET}
jwt.email.verification.token.expiration=900000
jwt.access.token.secret=${JWT_ACCESS_TOKEN_SECRET}
jwt.access.token.expiration=
jwt.refresh.token.secret=${JWT_REFRESH_TOKEN_SECRET}
jwt.refresh.token.expiration=

# Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
