spring.application.name=ecommerce-api

spring.api.url=http://localhost:8080/api
spring.client.url=http://localhost:8080/api

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_boot_ecommerce_api
spring.datasource.username=postgres
spring.datasource.password=123rafi456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20

jwt.email.verification.token.secret=your-super-secret-key-min-32-character-123456
jwt.email.verification.token.expiration=900000
jwt.access.token.secret=
jwt.refresh.token.secret=

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nettpopp80@gmail.com
spring.mail.password=tccc zoud iipf ejin

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
